#!/usr/bin/env python3
"""
pack.py — flattens the Rojo source tree into two paste-in scripts for people
who don't want to install Rojo.

    python3 tools/pack.py

Outputs:
    build/PasteInto_ServerScriptService.server.lua   (a Script)
    build/PasteInto_StarterPlayerScripts.client.lua  (a LocalScript)

It works because every module imports through the single canonical line

    local Req = require(game:GetService("ReplicatedStorage"):WaitForChild("TungShared"):WaitForChild("Req"))

which the packer swaps for a local table lookup.
"""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
BUILD = ROOT / "build"

BOOTSTRAP = re.compile(
    r'^local\s+Req\s*=\s*require\(game:GetService\("ReplicatedStorage"\)'
    r':WaitForChild\("TungShared"\):WaitForChild\("Req"\)\)\s*$',
    re.MULTILINE,
)

HEADER = """--!nolint
--[[
	TUNG TUNG TYCOON — generated single-file build ({side}).
	DO NOT EDIT. Generated by tools/pack.py from src/.
	Source of truth is the Rojo project; regenerate after changing src/.
]]

local __MODULES = {{}}
local __CACHE = {{}}
local __LOADING = {{}}

local function __Req(name)
	local cached = __CACHE[name]
	if cached ~= nil then
		return cached
	end
	if __LOADING[name] then
		error("[Tung] circular dependency while loading " .. tostring(name), 2)
	end
	local factory = __MODULES[name]
	if not factory then
		error("[Tung] module not found in packed build: " .. tostring(name), 2)
	end
	__LOADING[name] = true
	local value = factory()
	__LOADING[name] = nil
	__CACHE[name] = value
	return value
end

"""


def strip_bootstrap(source: str) -> str:
    return BOOTSTRAP.sub("local Req = __Req", source)


def indent(source: str) -> str:
    return "\n".join(("\t" + line) if line.strip() else line for line in source.splitlines())


def module_block(name: str, source: str) -> str:
    body = indent(strip_bootstrap(source))
    return f'__MODULES["{name}"] = function()\n{body}\nend\n\n'


def collect(folder: Path):
    """Returns (modules, entries) for a source folder."""
    modules, entries = [], []
    for path in sorted(folder.glob("*.lua")) + sorted(folder.glob("*.luau")):
        stem = path.stem
        if stem == "Req":
            continue  # replaced by __Req
        if stem.endswith(".server") or stem.endswith(".client"):
            entries.append(path)
        else:
            modules.append(path)
    return modules, entries


def build(side: str, folders, out_path: Path):
    chunks = [HEADER.format(side=side)]
    entry_sources = []

    for folder in folders:
        modules, entries = collect(folder)
        for path in modules:
            chunks.append(module_block(path.stem, path.read_text(encoding="utf-8")))
        for path in entries:
            entry_sources.append(strip_bootstrap(path.read_text(encoding="utf-8")))

    if not entry_sources:
        raise SystemExit(f"no entry script (*.server.lua / *.client.lua) found for {side}")

    chunks.append("-- ── entry point ───────────────────────────────────────────────\n\n")
    chunks.extend(entry_sources)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(chunks), encoding="utf-8")
    return out_path


def main():
    server = build("server", [SRC / "shared", SRC / "server"],
                   BUILD / "PasteInto_ServerScriptService.server.lua")
    client = build("client", [SRC / "shared", SRC / "client"],
                   BUILD / "PasteInto_StarterPlayerScripts.client.lua")

    for path in (server, client):
        size = path.stat().st_size
        print(f"  {path.relative_to(ROOT)}  ({size/1024:.1f} KB)")


if __name__ == "__main__":
    main()
